# SPDX-License-Identifier: MIT-0

namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0

readme: README.md

authors:
  - Ilya Demin

description: Ansible collection with a custom module and role for creating text files on remote hosts.

license:
  - MIT

tags:
  - ansible
  - custom
  - module
  - role

dependencies: {}

repository: https://github.com/deminilyadev-maker/my_own_collection
documentation: https://github.com/deminilyadev-maker/my_own_collection
homepage: https://github.com/deminilyadev-maker/my_own_collection
issues: https://github.com/deminilyadev-maker/my_own_collection/issues

build_ignore: []
